version: '3'
services:
  ldbm:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5000:8000"
    depends_on:
      - ldbm